spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters: # Filtro por defecto de todas las requests realizadas al gateway
        - name: LogFilter
      discovery:
        Locator:
          enabled: true
      routes:
        - id: course
          uri: lb://course
          predicates:
            - Path=/api/v1/course/**
        - id: students
          uri: lb://students
          predicates:
            - Path=/api/v1/students/**